version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install tox

  pre_build:
    commands:
      - aws configure set default.region $AWS_REGION

  build:
    commands:
      - tox
