version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install tox

  pre_build:
    commands:
      - aws configure set default.region $AWS_REGION

  build:
    commands:
      - tox

  post_build:
    commands:
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file output-template.yml

artifacts:
  type: zip
  files:
    - template.yml
    - output-template.yml
